apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeturbo-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubeturbo-operator
  template:
    metadata:
      labels:
        name: kubeturbo-operator
    spec:
      serviceAccountName: kubeturbo-operator
      containers:
        - name: kubeturbo-operator
          # Replace this with the built image name
          image: icr.io/cpopen/kubeturbo-operator:8.9.2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubeturbo-operator"
          volumeMount:
            - mountPath: /tmp
              name: operator-tmpfs0
      volumes:
        - name: operator-tmpfs0
          emptyDir: {}
