# The configuration of communication to the OpsMgr server
apiVersion: v1
kind: ConfigMap
metadata:
  name: turbo-config
data:
  turbo.config: |-
    {
        "communicationConfig": {
            "serverMeta": {
                "version": "6.1.0-SNAPSHOT",
                "turboServer": "https://127.0.0.1:9400"
            },
            "restAPIConfig": {
                "opsManagerUserName": "administrator",
                "opsManagerPassword": "administrator"
            }
        }
    }