apiVersion: v1
kind: ServiceAccount
metadata:
  # use this yaml to create a service account to run kubeturbo.
  # Provide a value for name:
  # Update the namespace value if required
  name: turbo-user
  namespace: turbo