apiVersion: v1
kind: Namespace
metadata:
  # turbo is default value used in the samples provided
  name: turbo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  # Update the namespace value if required
  name: turbo-user
  namespace: turbo
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1    
metadata:
  # use this yaml to create a binding that will assign cluster-admin to your turbo ServiceAccount 
  # Provide a value for the binding name: and update namespace if needed
  name: turbo-all-binding
  namespace: turbo
subjects:
- kind: ServiceAccount
  # Provide the correct value for service account name: and namespace if needed
  name: turbo-user
  namespace: turbo
roleRef:
  # User creating this resource must have permissions to add this policy to the SA
  kind: ClusterRole
# for other limited cluster admin roles, see samples provided
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  # use this yaml to provide details kubeturbo will use to connect to the Turbo Server
  # requires Turbo Server and kubeturbo pod 6.4.3 and higher 
  # Provide a value for the config name: and update namespace if needed
  name: turbo-config
  namespace: turbo
data:
  # Update the values for version, turboServer, opsManagerUserName, opsManagerPassword
  # For version, use Turbo Server Version, even when running CWOM
  # The opsManagerUserName requires Turbo administrator role
  #
  # For targetConfig, targetName provides better group naming to identify k8s clusters in UI
  # - If no targetConfig is specified, a default targetName will be created from the apiserver URL in
  #   the kubeconfig.
  # - Specify a targetName only will register a probe with type Kubernetes-<targetName>, as well as
  #   adding your cluster as a target with the name Kubernetes-<targetName>.
  # - Specify a targetType only will register a probe without adding your cluster as a target.
  #   The probe will appear as a Cloud Native probe in the UI with a type Kubernetes-<targetType>.
  #
  #  ex:
  #  "serverMeta": {
  #    "proxy":  "http://username:password@ip:port or http://ip:port"
  #  }
  #
  # Define node groups by node role, and automatically enable placement policies to limit to 1 per host
  # DaemonSets are identified by default. Use daemonPodDetectors to identify by name patterns using regex or by namespace.
  #
  # serverMeta.proxy format for authenticated and non-authenticated "http://username:password@ip:port or http://ip:port"
  
  turbo.config: |-
    {
        "communicationConfig": {
            "serverMeta": {
                "version": "8.2",
                "turboServer": "https://<Turbo_server_URL>"
            },
            "restAPIConfig": {
                "opsManagerUserName": "<Turbo_username>",
                "opsManagerPassword": "<Turbo_password>"
            }
        },
        "targetConfig": {
            "targetName":"whateverYouWant"
        },
        "HANodeConfig": {
            "nodeRoles": [ "master"]
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # use this yaml to deploy the kubeturbo pod 
  # Provide a value for the deploy/pod name: and update namespace if needed
  name: kubeturbo
  namespace: turbo
spec:
  replicas: 1
  selector:
     matchLabels:
       app.kubernetes.io/name: kubeturbo
  template:
    metadata:
      annotations:
        kubeturbo.io/monitored: "false"
      labels:
        app.kubernetes.io/name: kubeturbo
    spec:
      # Update serviceAccount if needed
      serviceAccount: turbo-user
      containers:
      - name: kubeturbo
        # Replace the image with desired version:6.4.4 or latest
        image: turbonomic/kubeturbo:8.5.0
        env:
          - name: KUBETURBO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
          - --turboconfig=/etc/kubeturbo/turbo.config
          - --v=2
          # Comment out the following two args if running in k8s 1.10 or older, or
          # change to https=false and port=10255 if unsecure kubelet read only is configured
          - --kubelet-https=true
          - --kubelet-port=10250
          # Uncomment for pod moves in OpenShift
          #- --scc-support=*
          # Uncomment for pod moves with pvs
          #- --fail-volume-pod-moves=false
          # Uncomment to override default, and specify your own location
          #- --busybox-image=docker.io/busybox
          # or uncomment below to pull from RHCC
          #- --busybox-image=registry.access.redhat.com/ubi8/ubi-minimal
          # Uncomment to specify the secret name which holds the credentials to busybox image
          #- --busybox-image-pull-secret=<secret-name>
          # Specify nodes to exclude from cpu frequency getter job.
          # Note kubernetes.io/os=windows and/or beta.kubernetes.io/os=windows labels will be automatically excluded by default.
          # If specified all the labels will be used to select the node ignoring the default.
          #- --cpufreq-job-exclude-node-labels=kubernetes.io/key=value
          # Uncomment to stitch using IP, or if using Openstack, Hyper-V/VMM
          #- --stitch-uuid=false
          # Uncomment to customize readiness retry threshold. Kubeturbo will try readiness-retry-threshold times before giving up. Default is 60. The retry interval is 10s.
          #- --readiness-retry-threshold=60
        volumeMounts:
          # volume will be created, any name will work and must match below
          - name: turbo-volume
            mountPath: /etc/kubeturbo
            readOnly: true
          - name: turbonomic-credentials-volume
            # This mount path cannot be changed
            mountPath: /etc/turbonomic-credentials
            readOnly: true
          - name: varlog
            mountPath: /var/log
      volumes:
      - name: turbo-volume
        configMap:
         # Update configMap name if needed
          name: turbo-config
      - name: turbonomic-credentials-volume
        secret:
          defaultMode: 420
          optional: true
          # Update secret name if needed
          secretName: turbonomic-credentials
      - name: varlog
        emptyDir: {}
      restartPolicy: Always
---
#option to use secret for Turbo credentials
apiVersion: v1
kind: Secret
metadata:
  name: turbonomic-credentials
  namespace: turbo
type: Opaque
data:
  username: BASE64encodedValue
  password: BASE64encodedValue
---
